package Terceros;


/**
* Terceros/TerceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Terceros.idll
* miércoles 26 de septiembre de 2018 09:25:44 PM COT
*/

public interface TerceroOperations 
{
  boolean insertarTercero (String nombre, String apellidos, String telefono);
  boolean actualizarTercero (int id, String nombre, String apellidos, String telefono);
  boolean eliminarTercero (int id);
  boolean consultarTercero (int id);
  void shutdwn ();
} // interface TerceroOperations
